from schema.response.QuestionListPlaceSchema import QuestionListItemPlaceSchema, QuestionListSpecificPlaceSchema
from schema.response.QuestionListFoodSchema import QuestionListItemFoodSchema, QuestionListSpecificFoodSchema

placesQuestionList: list[QuestionListItemPlaceSchema] = [
    QuestionListItemPlaceSchema(
        phase=1,
        question_list=[
            QuestionListSpecificPlaceSchema(
                id=1,
                text="resturant"
            ),
            QuestionListSpecificPlaceSchema(
                id=2,
                text="caffee"
            ),
            QuestionListSpecificPlaceSchema(
                id=3,
                text="cinema"
            ),
            QuestionListSpecificPlaceSchema(
                id=4,
                text="park"
            ),
        ]
    ),
]

foodsQuestionList: list[QuestionListItemFoodSchema] = [
    QuestionListItemFoodSchema(
        phase=2,
        question_list=[
            QuestionListSpecificFoodSchema(
                id=1,
                food="pizza"
            ),
            QuestionListSpecificFoodSchema(
                id=2,
                food="burgur"
            ),
            QuestionListSpecificFoodSchema(
                id=3,
                food="pasta"
            ),
            QuestionListSpecificFoodSchema(
                id=4,
                food="steak"
            ),
            QuestionListSpecificFoodSchema(
                id=5,
                food="fried_chiken"
            ),
            QuestionListSpecificFoodSchema(
                id=6,
                food="coffee"
            ),
            QuestionListSpecificFoodSchema(
                id=7,
                food="cake"
            ),
            QuestionListSpecificFoodSchema(
                id=8,
                food="cheese_cake"
            ),
            QuestionListSpecificFoodSchema(
                id=9,
                food="ice_cream"
            ),
            QuestionListSpecificFoodSchema(
                id=10,
                food="pancake"
            ),
            QuestionListSpecificFoodSchema(
                id=11,
                food="hot_chocolate"
            ),
            QuestionListSpecificFoodSchema(
                id=12,
                food="popcorn"
            ),
            QuestionListSpecificFoodSchema(
                id=13,
                food="soda"
            ),
            QuestionListSpecificFoodSchema(
                id=14,
                food="nacho"
            ),
            QuestionListSpecificFoodSchema(
                id=15,
                food="chocolate"
            ),
            QuestionListSpecificFoodSchema(
                id=16,
                food="deep_fries"
            ),
            QuestionListSpecificFoodSchema(
                id=17,
                food="fruit_juice"
            ),
            QuestionListSpecificFoodSchema(
                id=18,
                food="ice_cream"
            ),
            QuestionListSpecificFoodSchema(
                id=19,
                food="coffee"
            ),
            QuestionListSpecificFoodSchema(
                id=20,
                food="fruit_juice"
            ),
            QuestionListSpecificFoodSchema(
                id=21,
                food="tea"
            ),
            QuestionListSpecificFoodSchema(
                id=22,
                food="fry"
            ),
            QuestionListSpecificFoodSchema(
                id=23,
                food="pop_corn"
            ),
        ]
    )
]